apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: portal
  name: portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/pipelines-demo/portal:latest
          imagePullPolicy: Always
          name: portal
          ports:
            - containerPort: 80
              protocol: TCP
  triggers:
     - type: ConfigChange
     - imageChangeParams:
         automatic: true
         containerNames:
           - portal
         from:
           kind: ImageStreamTag
           name: 'portal:latest'
           namespace: pipelines-demo
         lastTriggeredImage: >-
           image-registry.openshift-image-registry.svc:5000/pipelines-demo/portal:latest
       type: ImageChange
