kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: "2020-01-26T13:26:12Z"
  labels:
    app: portal
  name: portal
  namespace: pipelines-demo
  resourceVersion: "136470880"
spec:
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    deploymentconfig: portal
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
